apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bashreplicasets.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
              enum:
                - example.com/v1
            kind:
              type: string
              enum:
                - BashReplicaSet
            metadata:
              type: object
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  format: int32
                  minimum: 0
                selector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            type: array
                            items:
                              type: string
                template:
                  type: object
                  properties:
                    metadata:
                      type: object
                      properties:
                        labels:
                          type: object
                          additionalProperties:
                            type: string
                    spec:
                      type: object
                      properties:
                        containers:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              image:
                                type: string
                              ports:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    containerPort:
                                      type: integer
                                      format: int32
                                    protocol:
                                      type: string
            status:
              type: object
              properties:
                replicas:
                  type: integer
                  format: int32
                fullyLabeledReplicas:
                  type: integer
                  format: int32
                readyReplicas:
                  type: integer
                  format: int32
                availableReplicas:
                  type: integer
                  format: int32
                observedGeneration:
                  type: integer
                  format: int64
  names:
    plural: bashreplicasets
    singular: bashreplicaset
    kind: BashReplicaSet
    shortNames:
      - brs
  scope: Namespaced
