apiVersion: example.com/v1
kind: BashReplicaSet
metadata:
  name: nginx-bashreplicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
